# Routing for Agences
liste_des_agences:
    path:     /admin/agences
    defaults: { _controller: CoreBundle:Agence:index }

add_agence:
    path:     /admin/agences/add
    defaults: { _controller: CoreBundle:Agence:add }

remove_agence:
    path:     /admin/agences/delete/{itemDelete}
    defaults: { _controller: CoreBundle:Agence:delete }

edit_agence:
    path:     /admin/agences/edit/{itemEdit}
    defaults: { _controller: CoreBundle:Agence:edit }