parameters:
    core.app_zendesk_ticket_link_manager.class: CoreBundle\Services\Manager\Applications\ZendeskTicketLinkManager
    core.app.odigo.num_tel_liste_manager.class: CoreBundle\Services\Manager\Applications\Odigo\OdigoTelListeManager
    core.app.orange.num_tel_liste_manager.class: CoreBundle\Services\Manager\Applications\Odigo\OrangeTelListeManager

services:
    core.app_zendesk_ticket_link_manager:
        class: %core.app_zendesk_ticket_link_manager.class%
        arguments: ['@doctrine']
    core.app.odigo.num_tel_liste_manager:
        class: %core.app.odigo.num_tel_liste_manager.class%
        arguments: ['@doctrine']
    core.app.orange.num_tel_liste_manager:
        class: %core.app.orange.num_tel_liste_manager.class%
        arguments: ['@doctrine']