parameters:
    core.app_zendesk_ticket_link_manager.class: CoreBundle\Services\Manager\Applications\ZendeskTicketLinkManager

    core.prosodie_odigo_manager.class: CoreBundle\Services\Manager\Applications\ProsodieOdigoManager
    core.entity.prosodie_odigo.class: CoreBundle\Entity\Applications\ProsodieOdigo
    core.entityname.prosodie_odigo.class: 'CoreBundle\Entity\Applications\ProsodieOdigo'

    core.app.odigo.odigo_num_tel_liste_manager.class: CoreBundle\Services\Manager\Applications\Odigo\OdigoTelListeManager
    core.entity.odigo.odigo_num_tel_liste_manager.class: CoreBundle\Entity\Applications\Odigo\OdigoTelListe
    core.entityname.odigo.odigo_num_tel_liste_manager.class: 'CoreBundle\Entity\Applications\Odigo\OdigoTelListe'

    core.app.odigo.orange_num_tel_liste_manager.class: CoreBundle\Services\Manager\Applications\Odigo\OrangeTelListeManager
    core.entity.odigo.orange_num_tel_liste_manager.class: CoreBundle\Entity\Applications\Odigo\OrangeTelListe
    core.entityname.odigo.orange_num_tel_liste_manager.class: 'CoreBundle\Entity\Applications\Odigo\OrangeTelListe'

    core.app.salesforce.profile_manager.class: CoreBundle\Services\Manager\Applications\Salesforce\SalesforceProfileManager
    core.entity.salesforce.profile_manager.class: CoreBundle\Entity\Applications\Salesforce\SalesforceProfile
    core.entityname.salesforce.profile_manager.class: 'CoreBundle\Entity\Applications\Salesforce\SalesforceProfile'

    core.app.salesforce.groupe_manager.class: CoreBundle\Services\Manager\Applications\Salesforce\SalesforceGroupeManager
    core.entity.salesforce.groupe_manager.class: CoreBundle\Entity\Applications\Salesforce\SalesforceGroupe
    core.entityname.salesforce.groupe_manager.class: 'CoreBundle\Entity\Applications\Salesforce\SalesforceGroupe'

    core.app.salesforce.token_store.class: CoreBundle\Services\Manager\Applications\Salesforce\SalesforceTokenStoreManager
    core.entity.salesforce.token_store.class: CoreBundle\Entity\Applications\Salesforce\SalesforceTokenStore
    core.entityname.salesforce.token_store.class: 'CoreBundle\Entity\Applications\Salesforce\SalesforceTokenStore'

    core.app.aramis.agency_manager.class: CoreBundle\Services\Manager\Applications\Aramis\AramisAgencyManager
    core.entity.aramis.agency_manager.class: CoreBundle\Entity\Applications\Aramis\AramisAgency
    core.entityname.aramis.agency_manager.class: 'CoreBundle\Entity\Applications\Aramis\AramisAgency'

services:
    core.app_zendesk_ticket_link_manager:
        class: %core.app_zendesk_ticket_link_manager.class%
        arguments: ['@doctrine']

    core.prosodie_odigo_manager:
        class: %core.prosodie_odigo_manager.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.prosodie_odigo.class%"]]
        - [setEntityName, ["%core.entityname.prosodie_odigo.class%"]]

    core.odigotelliste_manager:
        class: %core.app.odigo.odigo_num_tel_liste_manager.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.odigo.odigo_num_tel_liste_manager.class%"]]
        - [setEntityName, ["%core.entityname.odigo.odigo_num_tel_liste_manager.class%"]]

    core.orangetelliste_manager:
        class: %core.app.odigo.orange_num_tel_liste_manager.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.odigo.orange_num_tel_liste_manager.class%"]]
        - [setEntityName, ["%core.entityname.odigo.orange_num_tel_liste_manager.class%"]]

    core.salesforceprofile_manager:
        class: %core.app.salesforce.profile_manager.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.salesforce.profile_manager.class%"]]
        - [setEntityName, ["%core.entityname.salesforce.profile_manager.class%"]]

    core.salesforcegroupe_manager:
        class: %core.app.salesforce.groupe_manager.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.salesforce.groupe_manager.class%"]]
        - [setEntityName, ["%core.entityname.salesforce.groupe_manager.class%"]]

    core.salesforcetoken_store:
        class: %core.app.salesforce.token_store.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.salesforce.token_store.class%"]]
        - [setEntityName, ["%core.entityname.salesforce.token_store.class%"]]

    core.aramisagency_manager:
        class: %core.app.aramis.agency_manager.class%
        parent: core.abstract_manager
        calls:
        - [setEntity, ["%core.entity.aramis.agency_manager.class%"]]
        - [setEntityName, ["%core.entityname.aramis.agency_manager.class%"]]
