# Routing for Services
liste_des_services:
    path:     /admin/services
    defaults: { _controller: CoreBundle:Service:index }

add_service:
    path:     /admin/services/add
    defaults: { _controller: CoreBundle:Service:add }

remove_service:
    path:     /admin/services/delete/{itemDelete}
    defaults: { _controller: CoreBundle:Service:delete }

edit_service:
    path:     /admin/services/edit/{itemEdit}
    defaults: { _controller: CoreBundle:Service:edit }