parameters:
    zendesk.zendesk_service.class: ZendeskBundle\Services\ZendeskService

services:
    zendesk.zendesk_service:
        class: %zendesk.zendesk_service.class%
        calls:
        - [ setContainer , [ "@service_container" ]]
