# This file has been automatically generated by Com\AramisAuto\PHPreprocessor
#
# It holds all available configuration directives for the project.
# Commented out directives have been inherited from parent configuration files.
# Uncomment directives to affect a specific value for this configuration profile.

#app
#database.cohiba.host=127.0.0.1
#database.cohiba.port=null
#database.cohiba.name=aramiam
#database.cohiba.user=aramiam
#database.cohiba.password=n>SLy6NP

#mailer.transport.type=gmail
#mailer.transport.host=smtp.gmail.com
#mailer.transport.user=infos.support@aramisauto.com
#mailer.transport.password=n>SLy6NP

#saml.entity.id=https=//aramiam.aramisauto.com
#saml.metadata.file=federationmetadata-adfs02.xml
#saml.logout.url=https=//adfs.aramisauto.com=1723/adfs/ls/?wa=wsignout1.0

#zendesk_api
#zendesk.api.key=YCrSZ5HBPH0epAsDRoyiwpmPggvD2Z0HI8Zn3q7R
#zendesk.api.user=zendesk@aramisauto.com
#zendesk.api.url=https=//aramisauto.zendesk.com

#google_api
#google.api.file=iamapiaa@iamapiaa.iam.gserviceaccount.com
#google.api.certificat=iamapiaa-1a0fba77949f.p12
#google.api.account=xavier.arroues@aramisauto.com

#odigo
#odigo.api.url=https=//odigo5.prosodie.com/aramis-auto/servlet/services/Administration?wsdl
#odigo.api.login=ARAMIS_WS
#odigo.api.password=admin_ws

#active_directory
#odigo.api.host=ldaps=//92.243.28.90
#odigo.api.user=CN=aramiam syncho,CN=Users,DC=aramisauto,DC=local
#odigo.api.password=Pp8B5fygZ25mAW57
#odigo.api.basedn=OU=Aramis AUTO,DC=aramisauto,DC=local
#odigo.api.extension='@@aramisauto.local'

#salesforce
#odigo.api.consumerKey=3MVG99OxTyEMCQ3j2IJDM7fI0WHNCzZGapk9j_xp7qd.Uge5FHWpptgLzyMQoC5dUG4XgkuphCws2q.oX2Y2K
#odigo.api.secret=29481019521149316
#odigo.api.user=salesforce-admin@aramisauto.com
#odigo.api.password=CrmAdminVente2015
#odigo.api.urloauth=https=//login.salesforce.com/services/oauth2/token
#odigo.api.loginurl=https=//login.salesforce.com/

#aramis_api
#aramis.api.url=http=//ws.aramisauto.com/agencies

#odigo.auth.super_admin_group='GRP-Aramiam-SUPER_ADMIN'
#odigo.auth.admin_group='GRP-Aramiam-ADMIN'

#odigo_wsdl_error_createagent_codes
#odigo_wsdl_error_createagent_codes_0=L''utlisateur a été créé
#odigo_wsdl_error_createagent_codes_105=L''utilisateur existe déjà

#odigo_wsdl_error_creatuserwithtemplate_codes
#odigo_wsdl_error_creatuserwithtemplate_codes_0=L''utlisateur a été créé
#odigo_wsdl_error_creatuserwithtemplate_codes_3=L''utilisateur existe déjà

#odigo_wsdl_error_export_codes
#odigo_wsdl_error_export_codes=L''export s''est correctement exécuté

#odigo_wsdl_error_delete_codes
#odigo_wsdl_error_delete_codes=L''utlisateur a été supprimé