parameters:
    app.abstract_manager.class: AppBundle\Services\Manager\AbstractManager

    app.id_store.class: AppBundle\Store\IdStore

    app.user_creator.class: AppBundle\Security\User\UserCreator

    app.user_manager.class: AppBundle\Services\UserManager
    app.entity.user_manager.class: AppBundle\Entity\User
    app.entityname.user_manager.class: 'AppBundle\Entity\User'
    app.argname.user_manager.class: 'Cet Admin'

    app.security.acces_service.class: AppBundle\Services\Security\AccesService

    app.parameters_calls.class: AppBundle\Services\Manager\ParametersManager

    app.factory.abstract.class: AppBundle\Factory\AbstractFactory

services:
    app.id_store:
        class: '%app.id_store.class%'
        arguments:
            - "@=service('doctrine').getManager()"
            - "@lightsaml.system.time_provider"

    app.user_creator:
        class: '%app.user_creator.class%'
        arguments:
            - "@=service('doctrine').getManager()"
            - "@lightsaml_sp.username_mapper.simple"
            - "@google.google_user_api_service"
        calls:
            - [ setContainer , [ "@service_container" ]]
            - [ setSuperAdminGroup , ["%app.auth.ad.super_admin_group%"]]
            - [ setAdminGroup, ["%app.auth.ad.admin_group%"]]

    app.user_manager:
        class: '%app.user_manager.class%'
        parent: app.abstract_manager
        arguments: ['@doctrine']
        calls:
        - [setEntity, ["%app.entity.user_manager.class%"]]
        - [setEntityName, ["%app.entityname.user_manager.class%"]]
        - [setArgname, ["%app.argname.user_manager.class%"]]

    app.security.acces_service:
        class: '%app.security.acces_service.class%'
        calls:
        - [ setContainer , [ "@service_container" ]]

    app.parameters_calls:
        class: '%app.parameters_calls.class%'
        arguments: ['@doctrine']

    app.abstract_manager:
        class: '%app.abstract_manager.class%'
        abstract: true
        arguments: ['@doctrine', '@session']

    app.factory.abstract:
        class: '%app.factory.abstract.class%'
        abstract: true

    twig.extension.intl:
           class: Twig_Extensions_Extension_Intl
           tags:
               - { name: twig.extension }