# This file has been automatically generated by Com\AramisAuto\PHPreprocessor
#
# It holds all available configuration directives for the project.
# Commented out directives have been inherited from parent configuration files.
# Uncomment directives to affect a specific value for this configuration profile.

#app
#app_database_host=127.0.0.1
#app_database_port=null
#app_database_name=aramiam
#app_database_user=aramiam
#app_database_password=n>SLy6NP
#app_mailer_transport=gmail
#app_mailer_host=smtp.gmail.com
#app_mailer_user=infos.support@aramisauto.com
#app_mailer_password=n>SLy6NP
#app_light_saml_entity_id=https=//aramiam.aramisauto.com
#app_federation_metadata_file=federationmetadata-adfs02.xml
#app_adfs_logout_url=https=//adfs.aramisauto.com=1723/adfs/ls/?wa=wsignout1.0
#app_secret=79eddab5e98361d6ec1296ca52402e11ca1fc825
#zendesk_api_=
#zendesk_api_key=YCrSZ5HBPH0epAsDRoyiwpmPggvD2Z0HI8Zn3q7R
#zendesk_api_user=zendesk@aramisauto.com
#zendesk_api_url=https=//aramisauto.zendesk.com

#google_api
#google_api_user_app_account=iamapiaa@iamapiaa.iam.gserviceaccount.com
#google_api_certificat_name=iamapiaa-1a0fba77949f.p12
#google_api_admin_account=xavier.arroues@aramisauto.com

#odigo
#odigo_url=https=//odigo5.prosodie.com/aramis-auto/servlet/services/Administration?wsdl
#odigo_login=ARAMIS_WS
#odigo_password=admin_ws

#active_directory
#active_directory_ldaphost=ldaps=//92.243.28.90
#active_directory_ldapUsername=CN=aramiam syncho,CN=Users,DC=aramisauto,DC=local
#active_directory_ldapPassword=Pp8B5fygZ25mAW57
#active_directory_ldapBaseDN=OU=Aramis AUTO,DC=aramisauto,DC=local

#salesforce
#salesforce_consumerKey=3MVG99OxTyEMCQ3j2IJDM7fI0WHNCzZGapk9j_xp7qd.Uge5FHWpptgLzyMQoC5dUG4XgkuphCws2q.oX2Y2K
#salesforce_secret=29481019521149316
#salesforce_username=salesforce-admin@aramisauto.com
#salesforce_password=CrmAdminVente2015
#salesforce_urlAauth2=https=//login.salesforce.com/services/oauth2/token
#salesforce_loginUrl=https=//login.salesforce.com/

#aramis_api
#aramis_api_ws_agency_url=http=//ws.aramisauto.com/agencies

#odigo_wsdl_error_createagent_codes
#odigo_wsdl_error_createagent_codes_0=L''utlisateur a été créé
#odigo_wsdl_error_createagent_codes_105=L''utilisateur existe déjà

#odigo_wsdl_error_creatuserwithtemplate_codes
#odigo_wsdl_error_creatuserwithtemplate_codes_0=L''utlisateur a été créé
#odigo_wsdl_error_creatuserwithtemplate_codes_3=L''utilisateur existe déjà

#odigo_wsdl_error_export_codes
#odigo_wsdl_error_export_codes=L''export s''est correctement exécuté

#odigo_wsdl_error_delete_codes
#odigo_wsdl_error_delete_codes=L''utlisateur a été supprimé