# app/config/security_dev.yml
security:
    providers:
        app.db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            light_saml_sp:
                provider: app.db_provider       # user provider name configured in step 9
                user_creator: app.user_creator  # name of the user creator service created in step 10
                login_path: /saml/login
                check_path: /saml/login_check
            logout:
                path: /logout
                target: "%adfs_logout_url%"
            anonymous: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/ajax/$, role: ROLE_ADMIN }
        - { path: ^/admin/agences/$, role: ROLE_SUPER_ADMIN }
        - { path: ^/app/$, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/fonctions/$, role: ROLE_ADMIN }
        - { path: ^/admin/services/$, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/candidats/$, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/$, role: ROLE_USER }
        - { path: ^/$, role: ROLE_USER }